name: Build Tango Project
on:
  push:
    branches:
      - main
jobs:
  Build-Runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun install
      - name: Build Project
        run: bun run build
