name: Build Tango Project
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun install
      - name: Build Project
        run: bun run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tango-builds
          path: ./out
